# Generated by Django 4.0.2 on 2022-02-23 09:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gostinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_room', models.CharField(choices=[('ekonomy', 'ekonomy'), ('standart', 'standart'), ('lux', 'lux'), ('penthaus', 'penthaus'), ('prezident', 'prezident')], max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('time_left', models.CharField(choices=[(datetime.datetime(2022, 2, 24, 9, 3, 35, 244047), '1'), (datetime.datetime(2022, 2, 25, 9, 3, 35, 244068), '2'), (datetime.datetime(2022, 2, 26, 9, 3, 35, 244071), '3'), (datetime.datetime(2022, 2, 27, 9, 3, 35, 244073), '4'), (datetime.datetime(2022, 2, 28, 9, 3, 35, 244075), '5'), (datetime.datetime(2022, 3, 1, 9, 3, 35, 244077), '6'), (datetime.datetime(2022, 3, 2, 9, 3, 35, 244079), '7')], max_length=100)),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gostinica.menu')),
            ],
        ),
    ]
