# Generated by Django 4.0.2 on 2022-02-23 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostinica', '0003_alter_room_time_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='time_left',
            field=models.CharField(choices=[(datetime.datetime(2022, 2, 24, 9, 11, 56, 194246), '1'), (datetime.datetime(2022, 2, 25, 9, 11, 56, 194267), '2'), (datetime.datetime(2022, 2, 26, 9, 11, 56, 194270), '3'), (datetime.datetime(2022, 2, 27, 9, 11, 56, 194272), '4'), (datetime.datetime(2022, 2, 28, 9, 11, 56, 194275), '5'), (datetime.datetime(2022, 3, 1, 9, 11, 56, 194277), '6'), (datetime.datetime(2022, 3, 2, 9, 11, 56, 194279), '7')], max_length=100),
        ),
    ]
