# Generated by Django 4.0.2 on 2022-02-23 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostinica', '0004_alter_room_time_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='time_left',
            field=models.CharField(choices=[(datetime.datetime(2022, 2, 24, 9, 12, 52, 247729), '1'), (datetime.datetime(2022, 2, 25, 9, 12, 52, 247747), '2'), (datetime.datetime(2022, 2, 26, 9, 12, 52, 247750), '3'), (datetime.datetime(2022, 2, 27, 9, 12, 52, 247752), '4'), (datetime.datetime(2022, 2, 28, 9, 12, 52, 247754), '5'), (datetime.datetime(2022, 3, 1, 9, 12, 52, 247756), '6'), (datetime.datetime(2022, 3, 2, 9, 12, 52, 247758), '7')], max_length=100),
        ),
    ]
