# Generated by Django 4.0.2 on 2022-02-23 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostinica', '0005_alter_room_time_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='time_left',
            field=models.CharField(choices=[(datetime.datetime(2022, 2, 24, 9, 13, 17, 708787), '1'), (datetime.datetime(2022, 2, 25, 9, 13, 17, 708807), '2'), (datetime.datetime(2022, 2, 26, 9, 13, 17, 708810), '3'), (datetime.datetime(2022, 2, 27, 9, 13, 17, 708812), '4'), (datetime.datetime(2022, 2, 28, 9, 13, 17, 708814), '5'), (datetime.datetime(2022, 3, 1, 9, 13, 17, 708817), '6'), (datetime.datetime(2022, 3, 2, 9, 13, 17, 708819), '7')], max_length=100),
        ),
    ]
