# Generated by Django 4.0.2 on 2022-02-25 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostinica', '0006_alter_room_time_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='time_left',
            field=models.CharField(choices=[(datetime.datetime(2022, 2, 26, 12, 25, 37, 878870), '1'), (datetime.datetime(2022, 2, 27, 12, 25, 37, 878870), '2'), (datetime.datetime(2022, 2, 28, 12, 25, 37, 878870), '3'), (datetime.datetime(2022, 3, 1, 12, 25, 37, 878870), '4'), (datetime.datetime(2022, 3, 2, 12, 25, 37, 878870), '5'), (datetime.datetime(2022, 3, 3, 12, 25, 37, 878870), '6'), (datetime.datetime(2022, 3, 4, 12, 25, 37, 878870), '7')], max_length=100),
        ),
    ]
